apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: default
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-alert
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: k8s/argocd
    repoURL: https://github.com/cuongnd-scs/argocd.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true