apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications
  namespace: default
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: k8s/argocd-notifications
    repoURL: https://github.com/cuongnd-scs/argocd.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true