---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'user-service'
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-alert
spec:
  destination:
    # name: ''
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'project1/dev/user-service'
    repoURL: 'https://github.com/cuongnd-scs/argocd.git'
    targetRevision: develop
  project: 'default'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
